name: commandhelper
version: stable
version-script: git -C parts/commandhelper/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
  The Fuck tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  commandhelper:
    command: bin/commandhelper
    environment:
        PYTHONIOENCODING: utf-8
  fuck:
    command: bin/fuck
    environment:
        PYTHONIOENCODING: utf-8

parts:
  commandhelper:
    source: https://github.com/sma-abyar/commandhelper.git
    plugin: python
